# Generated by Django 5.0.3 on 2024-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackcofferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(max_length=50)),
                ('intensity', models.IntegerField(default=0)),
                ('sector', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('insight', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=50)),
                ('start_year', models.CharField(max_length=4)),
                ('impact', models.CharField(max_length=20)),
                ('added', models.CharField(max_length=50)),
                ('published', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('relevance', models.IntegerField(default=0)),
                ('pastle', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('likelihood', models.IntegerField(default=0)),
            ],
        ),
    ]
