# Generated by Django 5.0.3 on 2024-03-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blackcofferdata',
            old_name='pastle',
            new_name='pestle',
        ),
    ]
