# Generated by Django 5.0.3 on 2024-03-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0002_rename_pastle_blackcofferdata_pestle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='insight',
            field=models.CharField(max_length=255),
        ),
    ]
