# Generated by Django 5.0.3 on 2024-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0003_alter_blackcofferdata_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='added',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='end_year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='impact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='pestle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='published',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='sector',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blackcofferdata',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
