# Generated by Django 5.0.3 on 2024-03-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0005_alter_blackcofferdata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='url',
            field=models.URLField(),
        ),
    ]
