# Generated by Django 5.0.3 on 2024-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0006_alter_blackcofferdata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
