# Generated by Django 5.0.3 on 2024-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0007_alter_blackcofferdata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='intensity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
