# Generated by Django 5.0.3 on 2024-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0008_alter_blackcofferdata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='intensity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
