# Generated by Django 5.0.3 on 2024-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0009_alter_blackcofferdata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='likelihood',
            field=models.CharField(max_length=50),
        ),
    ]
