# Generated by Django 5.0.3 on 2024-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackcofferVisualizations', '0010_alter_blackcofferdata_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcofferdata',
            name='relevance',
            field=models.CharField(max_length=50),
        ),
    ]
